# Generated by Django 5.1.5 on 2025-08-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_intake_unique_together'),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('class', 'Class Event'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('meeting', 'Meeting'), ('holiday', 'Holiday'), ('sports', 'Sports'), ('other', 'Other')], default='class', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_all_day',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Core.term'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('branch', 'Branch Only'), ('department', 'Department Only'), ('course', 'Course Only'), ('class', 'Class Only'), ('students', 'Students Only'), ('classreps', 'Class Representatives Only'), ('staff', 'Staff Only'), ('classtutors', 'Class Tutors Only'), ('admins', 'Administrators Only'), ('private', 'Private')], default='private', max_length=20, null=True),
        ),
    ]
