# Generated by Django 5.1.5 on 2025-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_created_at_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(blank=True, choices=[('danger', 'Danger'), ('success', 'Success'), ('primary', 'Primary'), ('warning', 'Warning'), ('info', 'Info')], default='primary', max_length=20, null=True),
        ),
    ]
