# Generated by Django 5.1.5 on 2025-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(blank=True, default='primary', max_length=20, null=True),
        ),
    ]
