# Generated by Django 5.1.5 on 2025-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_event_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Event'), ('class', 'Class Event'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('meeting', 'Meeting'), ('holiday', 'Holiday'), ('sports', 'Sports'), ('other', 'Other')], default='personal', max_length=50, null=True),
        ),
    ]
