# Generated by Django 5.1.5 on 2025-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal Event'), ('Class', 'Class Event'), ('Exam', 'Exam'), ('Assignment', 'Assignment'), ('Meeting', 'Meeting'), ('Holiday', 'Holiday'), ('Sports', 'Sports'), ('Other', 'Other')], default='Personal', max_length=50, null=True),
        ),
    ]
