# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('NEW STUDENT', 'New Student'), ('CONTINUING', 'Continuing')], default='NEW STUDENT', max_length=15, null=True, verbose_name='Application Type')),
                ('regno', models.CharField(blank=True, max_length=40, null=True, verbose_name='Registration Number')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('sname', models.CharField(max_length=30, verbose_name='Sir Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('nat_id', models.IntegerField(blank=True, null=True, verbose_name='National ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('phy_addr', models.CharField(max_length=50, verbose_name='Physical Address')),
                ('home_addr', models.CharField(max_length=50, verbose_name='Home Address')),
                ('guardian_fname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian First Name')),
                ('guardian_lname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Last Name')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_phone', models.IntegerField(blank=True, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Relationship')),
                ('examtype', models.CharField(max_length=50, verbose_name='Previous Exams Type')),
                ('examyear', models.IntegerField(blank=True, null=True)),
                ('prev_schoolname', models.CharField(max_length=150, verbose_name='Previous School Name')),
                ('examgrade', models.CharField(max_length=50, verbose_name='Previous Grade')),
                ('previousexams', models.ImageField(upload_to='uploads/')),
                ('passport', models.ImageField(upload_to='students/')),
                ('doa', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Application')),
                ('state', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Joined', 'Joined')], default='Pending', max_length=40, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake')),
                ('module', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sponsor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='RegistrationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=100, verbose_name='Random Code')),
                ('doe', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Enquiry')),
                ('valid_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Expiry')),
                ('temporary', models.BooleanField(default=True, verbose_name='Temporary Number')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear', verbose_name='Academic Year')),
            ],
            options={
                'verbose_name': 'Registration Number',
                'verbose_name_plural': 'Registration Numbers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('sname', models.CharField(max_length=30, verbose_name='Sir Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('nat_id', models.IntegerField(blank=True, verbose_name='National ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('state', models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled'), ('Cleared', 'Cleared'), ('Differ', 'Differ'), ('Inactive', 'Inactive')], default='Active', max_length=30, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake')),
                ('sponsor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.sponsor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Allocate_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('state', models.CharField(choices=[('Allocated', 'Allocated'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('doa', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.class')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
                ('studentno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
            options={
                'verbose_name': 'Student Allocation',
                'verbose_name_plural': 'Students Allocation',
                'unique_together': {('studentno', 'term')},
            },
        ),
    ]
