# Generated by Django 5.1.5 on 2025-05-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='module',
        ),
    ]
