# Generated by Django 5.1.5 on 2025-07-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_remove_application_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate_student',
            name='studentno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Students.student'),
        ),
    ]
