# Generated by Django 5.1.5 on 2025-08-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_course_module_duration_alter_course_dor'),
        ('Students', '0003_alter_allocate_student_studentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Core.course'),
        ),
    ]
