# Generated by Django 5.1.5 on 2025-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Graduated', 'Graduated'), ('Expelled', 'Expelled'), ('Cleared', 'Cleared'), ('Differ', 'Differ'), ('Inactive', 'Inactive')], default='Active', max_length=30, null=True),
        ),
    ]
