# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Administration', 'ADMINISTRATION'), ('Academic', 'ACADEMIC')], default='Academic', max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=20, unique=True, verbose_name='Abbreviation')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=25, verbose_name='Abbreviation')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('name', models.CharField(max_length=255)),
                ('motto', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('paddr', models.CharField(max_length=255, verbose_name='Physical Address')),
                ('tel_a', models.IntegerField(verbose_name='Telephone 1')),
                ('tel_b', models.IntegerField(blank=True, null=True, verbose_name='Telephone 2')),
                ('email', models.EmailField(max_length=254)),
                ('newsystem', models.BooleanField(default=True)),
                ('dof', models.DateTimeField(blank=True, null=True, verbose_name='Date Founded')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('openingMonth', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=255, verbose_name='Opening Month')),
                ('closingMonth', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=25, verbose_name='Closing Month')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Registration')),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=25, verbose_name='Abbreviation')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name_plural': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Self', max_length=30, null=True, unique=True, verbose_name='Name')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('state', models.CharField(blank=True, choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE')], default='Active', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ('name', 'state'),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Main Campus', max_length=115, null=True, verbose_name='Branch Name')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Branch Code')),
                ('paddr', models.CharField(max_length=255, verbose_name='Physical Address')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('tel_a', models.IntegerField(verbose_name='Telephone 1')),
                ('tel_b', models.IntegerField(blank=True, null=True, verbose_name='Telephone 2')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address_front', models.CharField(blank=True, max_length=400, null=True)),
                ('ip_address_aux', models.CharField(blank=True, max_length=400, null=True)),
                ('dor', models.DateTimeField(auto_now_add=True, null=True)),
                ('front_activated', models.BooleanField(default=False)),
                ('aux_activated', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, choices=[('Active', 'Active'), ('Abandoned', 'Abandoned'), ('Inactive', 'Inactive')], default='Inactive', max_length=30, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
            ],
            options={
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=20, verbose_name='Abbreviation')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Regsitered')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
                ('members', models.ManyToManyField(blank=True, related_name='group_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake', verbose_name='Current Term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear', verbose_name='Current Year')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(blank=True, max_length=25, null=True, verbose_name='Abbreviation')),
                ('openingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('closingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear')),
            ],
            options={
                'verbose_name_plural': 'Intake Series',
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='users/', verbose_name="User's passport image")),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Duration(Terms)')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
            ],
            options={
                'verbose_name': 'Course Duration',
                'verbose_name_plural': 'Courses Durations',
                'unique_together': {('course', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('state', models.CharField(blank=True, choices=[('Active', 'Active'), ('Cleared', 'Cleared')], default='Active', max_length=30, null=True)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
            ],
            options={
                'verbose_name_plural': 'Class',
                'unique_together': {('name', 'intake')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncode', models.CharField(max_length=30, unique=True, verbose_name='Unit Code')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=20, verbose_name='Abbreviation')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('weekly_hours', models.IntegerField(blank=True, null=True, verbose_name='Weekly Hours')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'unique_together': {('uncode', 'abbr')},
            },
        ),
    ]
