# Generated by Django 5.1.5 on 2025-06-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_term_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='current_intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.intake', verbose_name='Current Term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='current_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear', verbose_name='Current Year'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
