# Generated by Django 5.1.5 on 2025-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_institution_current_intake_institution_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='tiktok',
            field=models.URLField(default=1, verbose_name='TikTok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='twitter',
            field=models.URLField(default=1, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='youtube',
            field=models.URLField(default=1, verbose_name='Youtube'),
            preserve_default=False,
        ),
    ]
