# Generated by Django 5.1.5 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_institution_facebook_institution_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
