# Generated by Django 5.1.5 on 2025-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_institution_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='newsystem',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
