# Generated by Django 5.1.5 on 2025-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
