# Generated by Django 5.1.5 on 2025-07-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='aux_activated',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='front_activated',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='ip_address_aux',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='ip_address_front',
        ),
    ]
