# Generated by Django 5.1.5 on 2025-08-04 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_classroom_aux_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module_duration',
            field=models.IntegerField(default=1, verbose_name='Module Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dor',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered'),
        ),
    ]
