# Generated by Django 5.1.5 on 2025-08-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_course_module_duration_alter_course_dor'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='promotionMode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
