# Generated by Django 5.1.5 on 2025-08-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_institution_promotionmode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='reg_intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes_registered', to='Core.term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_updated', to='Core.term'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'reg_intake')},
        ),
    ]
