# Generated by Django 5.1.5 on 2025-08-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_class_unique_together_class_reg_intake_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'reg_intake', 'branch')},
        ),
    ]
