# Generated by Django 5.1.5 on 2025-08-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intake',
            unique_together={('openingMonth', 'closingMonth')},
        ),
    ]
