# Generated by Django 5.1.5 on 2025-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_intake_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rating',
            field=models.CharField(blank=True, default='R0', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='total_topics',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
