# Generated by Django 5.1.5 on 2025-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_unit_is_published_unit_rating_unit_total_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
