# Generated by Django 5.1.5 on 2025-09-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_unit_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='rating',
        ),
    ]
