# Generated by Django 5.1.5 on 2025-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_remove_unit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
