# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='face_images/')),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_thumb', models.CharField(blank=True, max_length=10000, null=True)),
                ('left_pointingfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('left_middlefinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('left_ringfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('left_smallfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('right_thumb', models.CharField(blank=True, max_length=10000, null=True)),
                ('right_pointingfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('right_middlefinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('right_ringfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('right_smallfinger', models.CharField(blank=True, max_length=10000, null=True)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint Biometric',
                'verbose_name_plural': 'Fingerprints Biometrics',
            },
        ),
    ]
