# Generated by Django 5.1.5 on 2025-07-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biometrics', '0001_initial'),
        ('Core', '0009_remove_classroom_aux_activated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('location_hint', models.CharField(blank=True, max_length=255, null=True)),
                ('stream_url', models.URLField()),
                ('stream_type', models.CharField(choices=[('mjpeg', 'MJPEG'), ('hls', 'HLS'), ('webrtc', 'WebRTC')], default='mjpeg', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('front', 'Front Camera'), ('aux', 'Auxiliary Camera'), ('side', 'Side Camera')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='Core.classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
