# Generated by Django 5.1.5 on 2025-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biometrics', '0002_cameradevice_delete_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradevice',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
