# Generated by Django 5.1.5 on 2025-06-24 04:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0008_branch_latitude_branch_longitude'),
        ('Students', '0002_remove_application_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votehead', models.CharField(max_length=255, verbose_name='Vote Head')),
                ('abbr', models.CharField(max_length=25, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Fee Payment Account',
                'verbose_name_plural': 'Fee Payment Accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Priority Level',
                'verbose_name_plural': 'Priority Levels',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='FeeParticular',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
            ],
            options={
                'verbose_name': 'Fee Particular',
                'verbose_name_plural': 'Fee Particulars',
                'unique_together': {('course', 'module', 'term', 'account')},
            },
        ),
        migrations.CreateModel(
            name='FeeStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Overpaid', 'Overpaid'), ('Cleared', 'Cleared'), ('Not-Cleared', 'Not-Cleared')], max_length=25)),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.module', verbose_name='Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term', verbose_name='Academic Year')),
            ],
            options={
                'verbose_name': 'Fee Status',
                'verbose_name_plural': 'Fee Statuses',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Termly', 'Termly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=20)),
                ('datelastreminded', models.DateTimeField(auto_now=True, null=True)),
                ('datenextreminder', models.DateTimeField(blank=True, null=True)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.sponsor')),
            ],
            options={
                'verbose_name': 'Fee Payment Plan',
                'verbose_name_plural': 'Fee Payment Plans',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('trans_id', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cashier', models.CharField(max_length=50)),
                ('dop', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Payment')),
                ('is_finished', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('narration', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student', verbose_name='Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.feeparticular')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.receipt')),
            ],
            options={
                'verbose_name': 'Fee Transaction',
                'verbose_name_plural': 'Fee Transactions',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='brand/')),
                ('account_number', models.CharField(max_length=30)),
                ('expire_date', models.DateField()),
                ('blocked', models.BooleanField(default=False)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.wallet'),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('trans_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.wallet')),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
            },
        ),
        migrations.CreateModel(
            name='AccountPriorities',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.prioritylevel')),
            ],
            options={
                'verbose_name': 'Account Priority',
                'verbose_name_plural': 'Account Priorities',
                'unique_together': {('account', 'level', 'percentage')},
            },
        ),
    ]
