# Generated by Django 5.1.5 on 2025-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='color_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='color_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
