# Generated by Django 5.1.5 on 2025-06-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_wallet_color_from_wallet_color_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='color_from',
            new_name='bgClass',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='account_number',
            new_name='cardNumber',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='expire_date',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='icon',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='color_to',
        ),
    ]
