# Generated by Django 5.1.5 on 2025-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_rename_color_from_wallet_bgclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ccv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
