# Generated by Django 5.1.5 on 2025-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_wallet_account_number_wallet_ccv'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cardHolder',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
