# Generated by Django 5.1.5 on 2025-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_alter_wallet_blocked_alter_wallet_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
