# Generated by Django 5.1.5 on 2025-06-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_alter_wallet_blocked_alter_wallet_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Fee Account', 'verbose_name_plural': 'Fee Accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Finance.prioritylevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='AccountPriorities',
        ),
    ]
