# Generated by Django 5.1.5 on 2025-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_alter_account_options_account_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='paybill',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
