# Generated by Django 5.1.5 on 2025-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_wallet_paybill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentattempt',
            old_name='trans_id',
            new_name='checkout_request_id',
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='merchant_request_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
