# Generated by Django 5.1.5 on 2025-06-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0010_rename_trans_id_paymentattempt_checkout_request_id_and_more'),
        ('Students', '0002_remove_application_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentattempt',
            name='reference',
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.student'),
        ),
    ]
