# Generated by Django 5.1.5 on 2025-06-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_paymentattempt_ref_id_alter_paymentattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_successful',
        ),
    ]
