# Generated by Django 5.1.5 on 2025-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0013_remove_receipt_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
