# Generated by Django 5.1.5 on 2025-07-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_branch_latitude_branch_longitude'),
        ('Finance', '0014_transaction_running_balance'),
        ('Students', '0002_remove_application_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], default='Pending', max_length=30, null=True)),
                ('narration', models.ManyToManyField(related_name='invoices', to='Finance.feeparticular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student', verbose_name='Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='Finance.invoice'),
        ),
    ]
