# Generated by Django 5.1.5 on 2025-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0017_remove_receipt_invoice_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestatus',
            name='purpose',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
