# Generated by Django 5.1.5 on 2025-07-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0018_feestatus_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Finance.wallet'),
        ),
    ]
