# Generated by Django 5.1.5 on 2025-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0019_alter_receipt_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeparticular',
            name='individual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='mode',
            field=models.CharField(choices=[('Student', 'Student'), ('Course', 'Course')], default='Course', max_length=10),
        ),
    ]
