# Generated by Django 5.1.5 on 2025-07-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0020_feeparticular_individual_feeparticular_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeparticular',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='feeparticular',
            name='mode',
        ),
    ]
