# Generated by Django 5.1.5 on 2025-08-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0021_remove_feeparticular_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeparticular',
            name='target',
            field=models.CharField(choices=[('Student', 'Student'), ('Class', 'Class'), ('Course', 'Course')], default='Course', max_length=30),
        ),
    ]
