# Generated by Django 5.1.5 on 2025-08-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_class_unique_together_class_reg_intake_and_more'),
        ('Finance', '0022_feeparticular_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeparticular',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feeparticular',
            name='target',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Class', 'Class'), ('Course', 'Course')], default='Course', max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feeparticular',
            unique_together={('course', 'module', 'term', 'account', 'target')},
        ),
    ]
