# Generated by Django 5.1.5 on 2025-08-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0023_alter_feeparticular_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeparticular',
            unique_together=set(),
        ),
    ]
