# Generated by Django 5.1.5 on 2025-08-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_class_unique_together'),
        ('Finance', '0024_alter_feeparticular_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeparticular',
            unique_together={('name', 'course', 'module', 'term')},
        ),
    ]
