# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Registration Number')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('sname', models.CharField(max_length=30, verbose_name='Sir Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('nat_id', models.IntegerField(verbose_name='National ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('weekly_hours', models.IntegerField(blank=True, null=True, verbose_name='Weekly Hours')),
                ('dob', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Birth')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Transfered', 'Transfered'), ('Leave', 'Leave'), ('Retired', 'Retired')], default='Active', max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.designation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.userprofile')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ('fname', 'sname'),
            },
        ),
        migrations.CreateModel(
            name='ClassTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doa', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Assignment')),
                ('state', models.CharField(choices=[('Allocated', 'Allocated'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class')),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.staff')),
            ],
            options={
                'verbose_name': 'Class Tutor',
                'verbose_name_plural': 'Class Tutors',
                'unique_together': {('regno', 'Class')},
            },
        ),
        migrations.CreateModel(
            name='StaffWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doa', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Assignment')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class')),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.staff')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.unit')),
            ],
            options={
                'verbose_name': 'Staff Workload',
                'verbose_name_plural': 'Staffs Workloads',
                'unique_together': {('term', 'regno', 'unit', 'Class')},
            },
        ),
    ]
