# Generated by Django 5.1.5 on 2025-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='load_state',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Average', 'Average'), ('Available', 'Available')], default='Available', max_length=30, null=True, verbose_name='Load State'),
        ),
        migrations.AddField(
            model_name='staff',
            name='used_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Used Hours'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='weekly_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Weekly Hours'),
        ),
    ]
