# Generated by Django 5.1.5 on 2025-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_staff_load_state_staff_used_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='load_state',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Above Optimum', 'Above Optimum'), ('Average', 'Average'), ('Available', 'Available')], default='Available', max_length=30, null=True, verbose_name='Load State'),
        ),
    ]
