home_addresses = [
    "P.O. Box 1023, Nyeri 10100, Nyeri County",
    "P.O. Box 215, Machakos 90100, Machakos County",
    "P.O. Box 542, Eldoret 30100, Uasin Gishu County",
    "P.O. Box 88, Kisumu 40100, Kisumu County",
    "P.O. Box 104, Mombasa 80100, Mombasa County",
    "P.O. Box 674, Kericho 20200, Kericho County",
    "P.O. Box 324, Kitale 30200, Trans Nzoia County",
    "P.O. Box 89, Nanyuki 10400, Laikipia County",
    "P.O. Box 457, Kakamega 50100, Kakamega County",
    "P.O. Box 213, Bungoma 50200, Bungoma County",
    "P.O. Box 765, Voi 80300, Taita Taveta County",
    "P.O. Box 110, Embu 60100, Embu County",
    "P.O. Box 509, Meru 60200, Meru County",
    "P.O. Box 942, Thika 01000, Kiambu County",
    "P.O. Box 341, Keroka 40202, Nyamira County",
    "P.O. Box 111, Migori 40400, Migori County",
    "P.O. Box 223, Kitui 90200, Kitui County",
    "P.O. Box 909, Isiolo 60300, Isiolo County",
    "P.O. Box 312, Lodwar 30500, Turkana County",
    "P.O. Box 671, Wajir 70200, Wajir County",
    "P.O. Box 998, Garissa 70100, Garissa County",
    "P.O. Box 742, Mandera 70300, Mandera County",
    "P.O. Box 543, Siaya 40600, Siaya County",
    "P.O. Box 872, Bomet 20400, Bomet County",
    "P.O. Box 129, Narok 20500, Narok County",
    "P.O. Box 454, Kajiado 01100, Kajiado County",
    "P.O. Box 342, Naivasha 20117, Nakuru County",
    "P.O. Box 909, Gilgil 20116, Nakuru County",
    "P.O. Box 500, Nyahururu 20300, Laikipia County",
    "P.O. Box 879, Malindi 80200, Kilifi County",
    "P.O. Box 233, Lamu 80500, Lamu County",
    "P.O. Box 778, Tana River 70101, Tana River County",
    "P.O. Box 267, Marsabit 60500, Marsabit County",
    "P.O. Box 509, Chuka 60400, Tharaka-Nithi County",
    "P.O. Box 451, Ol Kalou 20303, Nyandarua County",
    "P.O. Box 562, Murang’a 10200, Murang’a County",
    "P.O. Box 679, Maralal 20600, Samburu County",
    "P.O. Box 712, Kapsabet 30300, Nandi County",
    "P.O. Box 892, Kabarnet 30400, Baringo County",
    "P.O. Box 546, Kapenguria 30600, West Pokot County",
    "P.O. Box 102, Moyale 60700, Marsabit County",
    "P.O. Box 742, Hola 70105, Tana River County",
    "P.O. Box 934, Kwale 80403, Kwale County",
    "P.O. Box 881, Kilifi 80108, Kilifi County",
    "P.O. Box 343, Ukunda 80400, Kwale County",
    "P.O. Box 226, Athi River 00204, Machakos County",
    "P.O. Box 529, Ruiru 00232, Kiambu County",
    "P.O. Box 781, Kangundo 90115, Machakos County",
    "P.O. Box 453, Mwingi 90400, Kitui County",
    "P.O. Box 635, Taveta 80302, Taita Taveta County",
    "P.O. Box 983, Kerugoya 10300, Kirinyaga County",
    "P.O. Box 145, Karatina 10101, Nyeri County",
    "P.O. Box 811, Othaya 10106, Nyeri County",
    "P.O. Box 294, Nyamira 40500, Nyamira County",
    "P.O. Box 111, Kisii 40200, Kisii County",
    "P.O. Box 235, Homa Bay 40300, Homa Bay County",
    "P.O. Box 764, Mbita 40305, Homa Bay County",
    "P.O. Box 276, Awendo 40405, Migori County",
    "P.O. Box 849, Kehancha 40413, Migori County",
    "P.O. Box 192, Migori 40400, Migori County",
    "P.O. Box 312, Oyugis 40222, Homa Bay County",
    "P.O. Box 788, Ndhiwa 40326, Homa Bay County",
    "P.O. Box 210, Sondu 40109, Kericho County",
    "P.O. Box 659, Londiani 20203, Kericho County",
    "P.O. Box 992, Litein 20210, Kericho County",
    "P.O. Box 563, Koru 40104, Kisumu County",
    "P.O. Box 671, Maseno 40105, Kisumu County",
    "P.O. Box 724, Yala 40602, Siaya County",
    "P.O. Box 111, Ugunja 40606, Siaya County",
    "P.O. Box 857, Luanda 50306, Vihiga County",
    "P.O. Box 315, Mbale 50300, Vihiga County",
    "P.O. Box 487, Kimilili 50204, Bungoma County",
    "P.O. Box 612, Webuye 50205, Bungoma County",
    "P.O. Box 934, Malaba 50209, Busia County",
    "P.O. Box 202, Busia 50400, Busia County",
    "P.O. Box 722, Port Victoria 50405, Busia County",
    "P.O. Box 588, Funyula 50406, Busia County",
    "P.O. Box 649, Amagoro 50210, Busia County",
    "P.O. Box 990, Lodwar 30500, Turkana County",
    "P.O. Box 454, Lokichar 30502, Turkana County",
    "P.O. Box 873, Kakuma 30503, Turkana County",
    "P.O. Box 672, Marigat 30405, Baringo County",
    "P.O. Box 555, Kabartonjo 30406, Baringo County",
    "P.O. Box 481, Mogotio 20105, Baringo County",
    "P.O. Box 798, Kajiado 01100, Kajiado County",
    "P.O. Box 134, Namanga 00207, Kajiado County",
    "P.O. Box 552, Kitengela 00241, Kajiado County",
    "P.O. Box 782, Ngong 00208, Kajiado County",
    "P.O. Box 362, Ongata Rongai 00511, Kajiado County",
    "P.O. Box 141, Magadi 00215, Kajiado County",
    "P.O. Box 939, Narok 20500, Narok County",
    "P.O. Box 245, Suswa 20506, Narok County",
    "P.O. Box 511, Kilgoris 40700, Narok County",
    "P.O. Box 728, Ololulung’a 20504, Narok County"
]

physical_addresses = [
    "Tom Mboya Street, Nairobi CBD, Nairobi County",
    "Moi Avenue, Mombasa Town, Mombasa County",
    "Kisumu-Kakamega Road, Kisumu City, Kisumu County",
    "Mama Ngina Drive, Mombasa, Mombasa County",
    "Kimathi Street, Nyeri Town, Nyeri County",
    "Uhuru Highway, Nairobi, Nairobi County",
    "Kenyatta Avenue, Nakuru Town, Nakuru County",
    "Oginga Odinga Street, Kisumu, Kisumu County",
    "Moi Avenue, Nairobi, Nairobi County",
    "Ronald Ngala Street, Nairobi, Nairobi County",
    "Moi Avenue, Voi Town, Taita Taveta County",
    "Digo Road, Mombasa, Mombasa County",
    "Ngong Road, Nairobi, Nairobi County",
    "Jogoo Road, Nairobi, Nairobi County",
    "Kenyatta Road, Nanyuki, Laikipia County",
    "Moi South Lake Road, Naivasha, Nakuru County",
    "Mombasa Road, Athi River, Machakos County",
    "Enterprise Road, Industrial Area, Nairobi County",
    "Thika Superhighway, Ruiru, Kiambu County",
    "Gikambura Road, Kikuyu, Kiambu County",
    "Kericho-Bomet Road, Kericho Town, Kericho County",
    "Kakamega-Webuye Road, Kakamega, Kakamega County",
    "Kajiado-Namanga Road, Kajiado Town, Kajiado County",
    "Kitui-Mwingi Road, Kitui Town, Kitui County",
    "Garissa Road, Thika Town, Kiambu County",
    "Moi Avenue, Kitale Town, Trans Nzoia County",
    "Moi Avenue, Eldoret Town, Uasin Gishu County",
    "Kapenguria-Lodwar Road, Lodwar, Turkana County",
    "Mandera-Wajir Road, Mandera Town, Mandera County",
    "Moyale Road, Isiolo Town, Isiolo County",
    "Wote Road, Machakos Town, Machakos County",
    "Kenyatta Street, Bungoma Town, Bungoma County",
    "Busia-Kisumu Road, Busia Town, Busia County",
    "Kisii-Migori Road, Kisii Town, Kisii County",
    "Migori-Homa Bay Road, Migori Town, Migori County",
    "Keroka-Sotik Road, Keroka Town, Nyamira County",
    "Maralal-Baragoi Road, Maralal Town, Samburu County",
    "Marsabit-Moyale Road, Marsabit Town, Marsabit County",
    "Hola-Garsen Road, Hola Town, Tana River County",
    "Lamu-Seafront, Lamu Town, Lamu County",
    "Kwale-Diani Road, Kwale Town, Kwale County",
    "Kilifi-Malindi Road, Kilifi Town, Kilifi County",
    "Ukunda-Diani Road, Ukunda, Kwale County",
    "Mombasa-Likoni Ferry, Likoni, Mombasa County",
    "Thika-Murang’a Road, Murang’a Town, Murang’a County",
    "Othaya-Karatina Road, Othaya, Nyeri County",
    "Karura Road, Karatina, Nyeri County",
    "Kerugoya-Kutus Road, Kerugoya, Kirinyaga County",
    "Chuka-Meru Road, Chuka Town, Tharaka-Nithi County",
    "Kitengela Road, Kitengela Town, Kajiado County",
    "Ngong-Kiserian Road, Ngong, Kajiado County",
    "Ongata Rongai-Magadi Road, Ongata Rongai, Kajiado County",
    "Magadi Road, Magadi Town, Kajiado County",
    "Suswa-Mai Mahiu Road, Suswa, Narok County",
    "Narok-Maasai Mara Road, Narok Town, Narok County",
    "Kilgoris-Lolgorian Road, Kilgoris, Narok County",
    "Bomet-Kaplong Road, Bomet Town, Bomet County",
    "Kericho-Litein Road, Litein, Kericho County",
    "Londiani-Molo Road, Londiani, Kericho County",
    "Maseno-Busia Road, Maseno Town, Kisumu County",
    "Yala-Ugunja Road, Yala, Siaya County",
    "Ugunja-Bondo Road, Ugunja Town, Siaya County",
    "Luanda-Mbale Road, Luanda, Vihiga County",
    "Mbale-Kaimosi Road, Mbale Town, Vihiga County",
    "Kimilili-Webuye Road, Kimilili, Bungoma County",
    "Webuye-Malaba Road, Webuye Town, Bungoma County",
    "Malaba-Eldoret Road, Malaba Town, Busia County",
    "Port Victoria-Bondo Road, Port Victoria, Busia County",
    "Funyula-Luanda Road, Funyula, Busia County",
    "Amagoro-Kocholya Road, Amagoro, Busia County",
    "Lokichar-Kakuma Road, Lokichar, Turkana County",
    "Kakuma-Lodwar Road, Kakuma Town, Turkana County",
    "Marigat-Lake Baringo Road, Marigat, Baringo County",
    "Kabartonjo-Mochongoi Road, Kabartonjo, Baringo County",
    "Mogotio-Eldama Ravine Road, Mogotio, Baringo County",
    "Namanga-Arusha Road, Namanga Town, Kajiado County",
    "Nakuru-Njoro Road, Nakuru Town, Nakuru County",
    "Nakuru-Gilgil Road, Gilgil Town, Nakuru County",
    "Gilgil-Naivasha Road, Naivasha Town, Nakuru County",
    "Ol Kalou-Ol Jororok Road, Ol Kalou, Nyandarua County",
    "Nyahururu-Rumuruti Road, Nyahururu, Laikipia County",
    "Isiolo-Nanyuki Road, Isiolo Town, Isiolo County",
    "Karatina-Nanyuki Road, Nanyuki Town, Laikipia County",
    "Kitale-Kapenguria Road, Kapenguria Town, West Pokot County",
    "Kapsabet-Nandi Hills Road, Kapsabet Town, Nandi County",
    "Eldoret-Iten Road, Iten Town, Elgeyo-Marakwet County",
    "Kericho-Kapkugerwet Road, Kapkugerwet, Kericho County",
    "Bondo-Usenge Road, Usenge Town, Siaya County",
    "Siaya-Rang’ala Road, Rang’ala, Siaya County",
    "Kisii-Ogembo Road, Ogembo Town, Kisii County",
    "Nyamira-Nyamira Road, Nyamira Town, Nyamira County"
]
