# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2000)),
                ('page', models.CharField(blank=True, max_length=2000, null=True)),
                ('ipaddress', models.GenericIPAddressField()),
                ('computer', models.CharField(max_length=2000)),
                ('dot', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of Trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audits Trails',
            },
        ),
    ]
