# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Week Day')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'Timetable Day',
                'verbose_name_plural': 'Timetable Days',
            },
        ),
        migrations.CreateModel(
            name='TableSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Lesson Name')),
                ('start', models.TimeField(max_length=25, unique=True, verbose_name='Start Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('code', models.CharField(blank=True, choices=[('Lesson', 'Lesson'), ('Break', 'Break')], default='Lesson', max_length=25, null=True, verbose_name='Mode')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'Timetable Setup',
                'verbose_name_plural': 'Timetable Setups',
            },
        ),
        migrations.CreateModel(
            name='DummyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.days')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.tablesetup')),
            ],
            options={
                'verbose_name': 'Dummy Timetable',
                'verbose_name_plural': 'Dummy Timetables',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Registered')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.classroom')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.days')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.tablesetup')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.term')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.staffworkload')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'unique_together': {('term', 'day', 'lesson', 'Class')},
            },
        ),
    ]
