# Generated by Django 5.1.5 on 2025-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=255)),
                ('dor', models.DateTimeField()),
                ('tor', models.TimeField()),
            ],
            options={
                'verbose_name': 'Lecturer Register',
                'verbose_name_plural': 'Lecturers Registers',
            },
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=255)),
                ('dor', models.DateTimeField()),
                ('tor', models.TimeField()),
            ],
            options={
                'verbose_name': 'Student Register',
                'verbose_name_plural': 'Students Registers',
            },
        ),
    ]
