# Generated by Django 5.1.5 on 2025-05-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0001_initial'),
        ('Core', '0001_initial'),
        ('Staff', '0001_initial'),
        ('Students', '0001_initial'),
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class'),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course'),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake'),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.staff'),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.timetable'),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.class'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.intake'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.timetable'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.academicyear'),
        ),
    ]
