# Generated by Django 5.1.5 on 2025-06-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregister',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='course',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='year',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='year',
        ),
        migrations.AlterField(
            model_name='staffregister',
            name='state',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='state',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=255),
        ),
    ]
