# Generated by Django 5.1.5 on 2025-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_remove_staffregister_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dor', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Register Mode',
                'verbose_name_plural': 'Register Modes',
            },
        ),
    ]
