# Generated by Django 5.1.5 on 2025-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_attendancemodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='dor',
            field=models.DateField(),
        ),
    ]
