# Generated by Django 5.1.5 on 2025-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_alter_studentregister_dor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregister',
            name='dor',
            field=models.DateField(),
        ),
    ]
